<?php

namespace App\Repository\Portal;

/**
 * FeatureAnnouncementDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureAnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectFeatureByRoleDate($role)
    {
        $today = new \DateTime();
        $today = $today->format('Y-m-d 00:00:00');
        $result = $this->createQueryBuilder('f')
            ->select('f.announcementHeader,f.gifName,f.id,f.guId')
            ->where('f.status=1')
            ->andWhere('f.startTime <= :today')
            ->andWhere('f.endTime >= :today')
            ->andWhere('f.roles LIKE :role')
            ->setParameter('role', '%' . $role . '%')
            ->setParameter('today', $today);

        return $result->getQuery()->getResult();
    }
}
