monolog:
    channels: ['generalapi','groupapi1','groupapi2','groupapi5','ldap', 'broadcast', 'exceptions', 'fmt', 'emailer', 'authentication']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
            
        generalapi:
            type: stream
            path: "%kernel.logs_dir%/generalapi.log"
            level: info
            channels: ['generalapi']
        
        groupapi1:
            type: stream
            path: "%kernel.logs_dir%/groupapi1.log"
            level: info
            channels: ['groupapi1']

        groupapi2:
            type: stream
            path: "%kernel.logs_dir%/groupapi2.log"
            level: info
            channels: ['groupapi2']

        groupapi5:
            type: stream
            path: "%kernel.logs_dir%/groupapi5.log"
            level: info
            channels: ['groupapi5']

        ldap:
            type: stream
            path: "%kernel.logs_dir%/ldap.log"
            level: info
            channels: ['ldap']

        authentication:
            type: stream
            path: "%kernel.logs_dir%/authentication.log"
            level: info
            channels: ['authentication']

        broadcast:
            type: stream
            path: "%kernel.logs_dir%/broadcast.log"
            level: info
            channels: ['broadcast']

        exceptions:
            type: stream
            path: "%kernel.logs_dir%/exceptions.log"
            level: info
            channels: ['exceptions']

        fmt:
            type: stream
            path: "%kernel.logs_dir%/fmt.log"
            level: info
            channels: ['fmt']

        emailer:
            type: stream
            path: "%kernel.logs_dir%/emailer.log"
            level: info
            channels: ['emailer']
